# Generated by Django 3.2.3 on 2021-06-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('postgres', 'postgres'), ('pymysql', 'pymysql'), ('pyodbc', 'pyodbc'), ('oracle', 'oracle')], default='postgres', max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('dbname', models.CharField(max_length=255)),
            ],
        ),
    ]
