# Generated by Django 3.2.3 on 2021-05-21 11:59

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Irfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repd', models.DateTimeField(help_text='report date for the portfolio', verbose_name='DATE_OPER')),
                ('resd', models.DateTimeField(help_text='date of restructuring', verbose_name='REST_NEW')),
                ('st_date', models.DateTimeField(help_text='loan origination date', verbose_name='DATE_OPEN')),
                ('end_date', models.DateTimeField(help_text='contractual loan maturity date', verbose_name='DATE_PLANCLOSE')),
                ('bthday', models.DateTimeField(help_text='date of birth', verbose_name='DATEOFBIRTH')),
                ('dp', models.IntegerField(help_text='days principal is past due', verbose_name='OVERDUEDAY')),
                ('di', models.IntegerField(help_text='days interest is past due', verbose_name='INTEREST_OVERDUEDAY')),
                ('anp_m', models.DecimalField(decimal_places=10, help_text='normal principal amount in manats', max_digits=19, verbose_name='SUMMAAZN')),
                ('anp_c', models.DecimalField(decimal_places=10, help_text='normal principal amount in currency', max_digits=19, verbose_name='SUMMA')),
                ('aop_m', models.DecimalField(decimal_places=10, help_text='overdue principal amount in manats', max_digits=19, verbose_name='SUMMA_19AZN')),
                ('aop_c', models.DecimalField(decimal_places=10, help_text='overdue principal amount in currency', max_digits=19, verbose_name='SUMMA_19')),
                ('ani_m', models.DecimalField(decimal_places=10, help_text='normal interest amount in manats', max_digits=19, verbose_name='PROCAZN')),
                ('ani_c', models.DecimalField(decimal_places=10, help_text='normal interest amount in currency', max_digits=19, verbose_name='PROC')),
                ('aoi_m', models.DecimalField(decimal_places=10, help_text='overdue interest amount in manats', max_digits=19, verbose_name='PROCPROSAZN')),
                ('aoi_c', models.DecimalField(decimal_places=10, help_text='overdue interest amount in currency', max_digits=19, verbose_name='PROCPROS')),
                ('aor_m', models.DecimalField(decimal_places=10, help_text='original amount in manats', max_digits=19, verbose_name='SUMMAKREAZN')),
                ('aor_c', models.DecimalField(decimal_places=10, help_text='original amount in currency', max_digits=19, verbose_name='SUMMAKRE')),
                ('int_rate', models.DecimalField(decimal_places=10, help_text='Interest rate', max_digits=19, verbose_name='PROCSTAVKRE')),
                ('id_l', models.IntegerField(help_text='contract (loan) ID if any', verbose_name='KOD1')),
                ('id_c', models.IntegerField(help_text='client ID', verbose_name='LICSCHKRE')),
                ('id_sub', models.IntegerField(help_text='subaccount (order of loan)')),
                ('cid', models.IntegerField(help_text='currency ID (or name)', verbose_name='KODVALUTI')),
                ('pid', models.IntegerField(help_text='product ID or name', verbose_name='TIPKREDITA')),
                ('plist', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('wrof', models.IntegerField(help_text='write-off status column', verbose_name='WROF')),
            ],
            options={
                'db_table': 'MF',
            },
        ),
    ]
