# Generated by Django 3.2.5 on 2021-07-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_databasecredentials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Irfs',
            new_name='Ifrs',
        ),
    ]
