# Generated by Django 3.2.5 on 2021-07-16 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20210716_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifrs',
            name='repd_period',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifrs',
            name='repd_end',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='ifrs',
            name='repd_start',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
