# Generated by Django 3.2.5 on 2021-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20210716_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifrs',
            name='plist',
        ),
        migrations.AddField(
            model_name='ifrs',
            name='plist_cons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ifrs',
            name='plist_corp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ifrs',
            name='plist_sole',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
