# Generated by Django 3.2.5 on 2021-07-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20210716_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifrs',
            name='plist_cons',
        ),
        migrations.RemoveField(
            model_name='ifrs',
            name='plist_corp',
        ),
        migrations.RemoveField(
            model_name='ifrs',
            name='plist_sole',
        ),
    ]
