# Generated by Django 3.2.5 on 2021-07-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20210716_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifrs',
            name='repd_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ifrs',
            name='repd_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
