# Generated by Django 3.2.5 on 2021-07-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_auto_20210716_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifrs',
            name='ctype',
        ),
        migrations.RemoveField(
            model_name='ifrs',
            name='ptype',
        ),
    ]
