# Generated by Django 3.2.5 on 2021-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_auto_20210716_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=255)),
            ],
        ),
    ]
