# Generated by Django 3.2.5 on 2021-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_plist'),
    ]

    operations = [
        migrations.AddField(
            model_name='plist',
            name='measure',
            field=models.CharField(choices=[('pd', 'pd'), ('lgd', 'lgd')], default='pd', max_length=50),
        ),
    ]
