# Generated by Django 3.2.5 on 2021-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_plist_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('act_date', models.DateField()),
                ('par_status', models.CharField(max_length=255)),
                ('original', models.BigIntegerField()),
                ('c0', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.CharField(max_length=255)),
            ],
        ),
    ]
