# Generated by Django 3.2.5 on 2021-08-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_lgd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lgd',
            old_name='act_date',
            new_name='ACT_DATE',
        ),
        migrations.RenameField(
            model_name='lgd',
            old_name='id',
            new_name='ID',
        ),
    ]
