# Generated by Django 3.2.5 on 2021-08-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0017_auto_20210810_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lgd',
            old_name='c0',
            new_name='C0',
        ),
        migrations.RenameField(
            model_name='lgd',
            old_name='cl',
            new_name='CL',
        ),
        migrations.RenameField(
            model_name='lgd',
            old_name='loss',
            new_name='LOSS',
        ),
        migrations.RenameField(
            model_name='lgd',
            old_name='original',
            new_name='ORIGINAL',
        ),
        migrations.RenameField(
            model_name='lgd',
            old_name='paid',
            new_name='PAID',
        ),
        migrations.RenameField(
            model_name='lgd',
            old_name='par_status',
            new_name='PAR_STATUS',
        ),
        migrations.RenameField(
            model_name='lgd',
            old_name='product',
            new_name='PRODUCT',
        ),
    ]
