# Generated by Django 3.2.5 on 2021-08-10 10:52

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_lgd_df'),
    ]

    operations = [
        migrations.CreateModel(
            name='PD_UPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
