# Generated by Django 3.2.5 on 2021-08-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_pd_upd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LGD',
        ),
    ]
