# Generated by Django 3.2.5 on 2021-08-10 12:21

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_delete_lgd'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dict', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
